apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-dev-pod02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/mehmetmgrsl/test-argocd.git
      revision: main
      directories:
      - path: 'other/*'
      - path: other/pods
        exclude: true  

  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/mehmetmgrsl/test-argocd.git
        revision: main
        path: '{{path}}'
        helm:
          values: |
            pod:
              name: pod2
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true