apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: nginx-helm-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/mehmetmgrsl/helm-chart-nginx.git
    targetRevision: HEAD

    helm:
        values: |
          replicaCount: 2

-    #helm:
-      #valueFiles:
-        #- values.yaml
-      #externalValueFiles:
-        #- repoURL: https://github.com/mehmetmgrsl/test-argocd.git
-          #targetRevision: main
-          #valueFiles:
-            #- helm-values.yaml
+  

    #helm:
    #  version: v3
      #values: |
         #{{ .Files.Get "helm-values.yaml" | indent 8 }}
    #repoURL: https://github.com/mehmetmgrsl/test-argocd.git
    #targetRevision: main




  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
