apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-dev-pod1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/mehmetmgrsl/test-argocd.git 
      revision: multi-app  
      directories:
      - path: other 
      - path: pods
        exclude: true 
  template:
    metadata:
      name: root-dev-pod1
    spec:
      project: "default"
      source:
        repoURL: https://github.com/mehmetmgrsl/test-argocd.git
        targetRevision: multi-app
        path: '{{path}}'
        helm:
          values: |
            pod:
              name: pod1
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true