apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-dev-pod01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: other
    repoURL: https://github.com/mehmetmgrsl/test-argocd.git
    targetRevision: main

    directory:
      ## exclude the pods directory
      include: '*'
      exclude: pods
    helm:
      values: |
        pod:
          name: pod1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true